name: Check new rules

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  check-webpage:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch webpage
        id: fetch-webpage
        run: echo "::set-output name=page::$(curl ${MAGIC_WEBPAGE_URL})"
        env:
          MAGIC_WEBPAGE_URL: ${{ secrets.MAGIC_WEBPAGE_URL }}

      - name: Search for rules
        id: search
        run: |
          if echo "${{ steps.fetch-webpage.outputs.page }}" | grep -q "${LAST_RULES_URL}"; then
            echo "::set-output name=found::true"
          else
            echo "::set-output name=found::false"
          fi
        env:
          LAST_RULES_URL: ${{ secrets.LAST_RULES_URL }}

      - name: Notify new rules
        if: steps.search.outputs.found == 'false'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            New Magic rules found. Update MTG Rules app
