name: Gradle

on:
  workflow_dispatch:
  push:
    branches: master
  pull_request:
    branches: master

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Create google-services.json
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES > $GITHUB_WORKSPACE/app/google-services.json
      - name: Build with Gradle
        run: ./gradlew build --stacktrace

  android-tests:
    runs-on: ubuntu-latest
    strategy:
      # We want to know if a failure happens just in one version or in all of them
      fail-fast: false
      matrix:
        api-level: [26, 35]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Create google-services.json
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES > $GITHUB_WORKSPACE/app/google-services.json
      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}
      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: default
          arch: x86_64
          profile: Nexus 4
          force-avd-creation: false
          emulator-options: -no-window -no-boot-anim -no-audio
          script: echo "Generated AVD snapshot for caching."
      - name: Run Android Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: default
          arch: x86_64
          profile: Nexus 4
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -no-boot-anim -no-audio
          script: ./gradlew connectedDebugAndroidTest --stacktrace
